
const D=window.IO_DATA; const $=s=>document.querySelector(s); const fmt=n=>Number(n).toFixed(3);
function mj(){ if(window.MathJax?.typesetPromise) MathJax.typesetPromise(); }
function side(){ const q=($('#search')?.value||'').toLowerCase(); $('#sideList').innerHTML='<h3>Inventarios</h3>'+D.modules.filter(m=>m.kind==='inventory'&&JSON.stringify(m).toLowerCase().includes(q)).map(m=>`<a class="module-link" href="#/modulo/${m.slug}">${m.title}</a>`).join('')+'<h3>Colas</h3>'+D.modules.filter(m=>m.kind==='queue'&&JSON.stringify(m).toLowerCase().includes(q)).map(m=>`<a class="module-link" href="#/modulo/${m.slug}">${m.title}</a>`).join('');}
function tbl(obj,cap='Datos del caso'){return `<table><caption>${cap}</caption><thead><tr><th>Parámetro</th><th>Valor</th></tr></thead><tbody>${Object.entries(obj).map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</tbody></table>`}
function progress(){let done=JSON.parse(localStorage.ioDone||'[]').length; return `<div class="card"><b>Progreso:</b> ${done}/${D.modules.length} módulos marcados.<div class="progress" aria-label="Progreso"><span style="width:${100*done/D.modules.length}%"></span></div></div>`}
function home(){return `<section class="card"><h1>Ecosistema web de Investigación de Operaciones</h1><p>Aprendizaje riguroso de inventarios y teoría de colas con MathJax, gráficos Chart.js, ejercicios, quices y tutor demo.</p><div class="alert">Las tablas de práctica usan datos simulados cuando no se declara una fuente verificable.</div></section>${progress()}<section class="grid">${D.modules.map(m=>`<article class="card"><h2>${m.title}</h2><p>${m.area}</p><a class="btn" href="#/modulo/${m.slug}">Abrir módulo</a></article>`).join('')}</section>`}
function modulePage(slug){const m=D.modules.find(x=>x.slug===slug); if(!m)return home(); let done=JSON.parse(localStorage.ioDone||'[]'); let html=`<article class="card"><p class="muted">Inicio › ${m.area} › ${m.title}</p><h1>${m.title}</h1><p><b>Modelo y supuestos.</b> Este módulo define variables, función objetivo/métricas, condiciones de aplicación y limitaciones. Fórmula guía: $$${m.formula}$$</p><div class="alert"><b>Lecturas recomendadas:</b> Anderson, Sweeney, Williams, Camm & Martin, capítulo de inventarios/colas; Winston, Operations Research; Hillier & Lieberman, Introduction to Operations Research.</div><button class="btn" onclick="markDone('${m.slug}')">Marcar módulo como completado</button></article>`;
 if(m.kind==='inventory') html+=inventoryLab(m); else html+=queueLab(m);
 html+=`<section class="card"><h2>10 ejemplos resueltos</h2>${m.examples.map(ex=>`<article class="example"><h3>${ex.title}</h3><p>${ex.statement}</p><p class="muted">Fuente: ${ex.source}</p>${tbl(ex.data)}<ol>${ex.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p><b>Interpretación:</b> ${ex.managerial}</p><details><summary>Errores comunes</summary><ul>${ex.errors.map(e=>`<li>${e}</li>`).join('')}</ul></details></article>`).join('')}</section><section class="card"><h2>Mini-resumen</h2><ul>${m.summary.map(x=>`<li>${x}</li>`).join('')}</ul></section>`; return html;}
function inventoryLab(m){return `<section class="card"><h2>Laboratorio interactivo de inventario</h2><div class="controls"><label>D demanda anual<input id="Dval" type="number" value="2400"></label><label>K costo ordenar<input id="Kval" type="number" value="80"></label><label>h mantener<input id="hval" type="number" value="4"></label><button class="btn" onclick="drawInventory()">Actualizar gráficos</button></div><p id="invOut" class="alert"></p><canvas id="invChart" aria-label="Inventario contra tiempo"></canvas><canvas id="costChart" aria-label="Costo total contra cantidad"></canvas></section>`}
function queueLab(m){return `<section class="card"><h2>Calculadora de colas</h2><div class="controls"><label>λ clientes/h<input id="lam" type="number" value="5" step=".1"></label><label>μ clientes/h<input id="mu" type="number" value="8" step=".1"></label><label>Servidores s<input id="serv" type="number" value="1"></label><button class="btn" onclick="calcQueue()">Calcular</button></div><p id="qOut" class="alert"></p></section>`}
let charts=[]; function clearCharts(){charts.forEach(c=>c.destroy()); charts=[]}
window.drawInventory=function(){clearCharts();let Dv=+$('#Dval').value,K=+$('#Kval').value,h=+$('#hval').value;if(Dv<=0||K<=0||h<=0){$('#invOut').textContent='Error: D, K y h deben ser positivos.';return}let Q=Math.sqrt(2*Dv*K/h); $('#invOut').innerHTML=`Q*=${fmt(Q)} unidades. CT anual sin compra=${fmt(Dv/Q*K+Q/2*h)}.`; let t=[0,.25,.5,.75,1].map(x=>x*Q/Dv*365); let inv=[Q,.75*Q,.5*Q,.25*Q,0]; charts.push(new Chart($('#invChart'),{type:'line',data:{labels:t.map(x=>fmt(x)),datasets:[{label:'Inventario (unidades)',data:inv}]},options:{plugins:{legend:{display:true}},scales:{x:{title:{display:true,text:'Días'}},y:{title:{display:true,text:'Unidades'}}}}})); let qs=Array.from({length:40},(_,i)=>Math.max(10,Q*.25+i*Q*.05)); charts.push(new Chart($('#costChart'),{type:'line',data:{labels:qs.map(x=>fmt(x)),datasets:[{label:'Costo total ($/año)',data:qs.map(q=>Dv/q*K+q/2*h)},{label:'Ordenar',data:qs.map(q=>Dv/q*K)},{label:'Mantener',data:qs.map(q=>q/2*h)}]},options:{scales:{x:{title:{display:true,text:'Q unidades'}},y:{title:{display:true,text:'$/año'}}}}}));}
window.calcQueue=function(){let l=+$('#lam').value,mu=+$('#mu').value,s=Math.max(1,+$('#serv').value); if(l<=0||mu<=0){$('#qOut').textContent='Error: λ y μ deben ser positivos.';return}let rho=l/(s*mu); if(rho>=1){$('#qOut').innerHTML=`ρ=${fmt(rho)}. Sistema inestable para cola infinita.`;return}let Lq=s===1?rho*rho/(1-rho):Math.pow(rho,s+1)/(1-rho); let Wq=Lq/l, W=Wq+1/mu, L=l*W; $('#qOut').innerHTML=`$$\\rho=${fmt(rho)},\\quad L_q=${fmt(Lq)},\\quad W_q=${fmt(Wq)}h,\\quad W=${fmt(W)}h,\\quad L=${fmt(L)}.$$`; mj();}
window.markDone=function(slug){let a=JSON.parse(localStorage.ioDone||'[]'); if(!a.includes(slug))a.push(slug); localStorage.ioDone=JSON.stringify(a); location.reload();}
function exercises(){return `<section class="card"><h1>Banco de ejercicios y casos</h1><p>Incluye ${D.exercises.length} problemas. Las soluciones están únicamente en Sitio B.</p></section>`+D.exercises.map(e=>`<article class="card"><h2>${e.id} · ${e.title}</h2><span class="pill">${e.difficulty}</span><span class="pill">${e.topic}</span><span class="pill">${e.time}</span><p>${e.context}</p><p class="muted">Fuente: ${e.source}</p>${tbl(e.data)}<ol>${e.questions.map(q=>`<li>${q}</li>`).join('')}</ol><label>Entrega del estudiante<textarea aria-label="Respuesta ${e.id}" data-answer="${e.id}" placeholder="Escriba aquí su solución..."></textarea></label></article>`).join('')}
function quizzes(){return `<section class="card"><h1>Quices interactivos</h1><button class="btn" onclick="randomQuiz()">Generar quiz aleatorio</button><div id="quizArea"></div></section>`+D.quizzes.map(q=>`<article class="card"><h2>${q.title}</h2><p>${q.questions.length} preguntas.</p><button class="btn" onclick="startQuiz('${q.id}')">Iniciar</button></article>`).join('')}
window.startQuiz=function(id){const qz=D.quizzes.find(q=>q.id===id); renderQuiz(qz.questions,qz.title)}; window.randomQuiz=function(){let pool=D.quizzes.flatMap(q=>q.questions); renderQuiz(pool.sort(()=>Math.random()-.5).slice(0,15),'Quiz aleatorio')}
function renderQuiz(qs,title){$('#quizArea').innerHTML=`<h2>${title}</h2>`+qs.map((q,i)=>`<div class="card"><b>${i+1}. ${q.prompt}</b>${q.type==='mc'?q.options.map((o,j)=>`<label class="quiz-option"><input name="q${i}" type="radio" value="${j}"> ${o}</label>`).join(''):q.type==='tf'?`<label><select id="ans${i}"><option value="true">Verdadero</option><option value="false">Falso</option></select></label>`:q.type==='num'?`<input id="ans${i}" type="number" step=".01">`:`<p>${Object.keys(q.pairs).join(', ')} ↔ ${Object.values(q.pairs).join(', ')}</p><input id="ans${i}" placeholder="D=demanda;K=costo...">`}<p id="fb${i}" class="muted"></p></div>`).join('')+`<button class="btn" onclick='gradeQuiz(${JSON.stringify(qs).replace(/'/g,"&#39;")})'>Calificar</button>`; mj()}
window.gradeQuiz=function(qs){let score=0; qs.forEach((q,i)=>{let ok=false;if(q.type==='mc'){let v=document.querySelector(`input[name=q${i}]:checked`); ok=v&&+v.value===q.answer}else if(q.type==='tf'){ok=($('#ans'+i).value==='true')===q.answer}else if(q.type==='num'){ok=Math.abs(+$('#ans'+i).value-q.answer)<=q.tol}else ok=($('#ans'+i).value||'').toLowerCase().includes('demanda'); if(ok)score++; $('#fb'+i).innerHTML=(ok?'Correcto. ':'Revisar. ')+q.feedback}); let hist=JSON.parse(localStorage.quizHist||'[]'); hist.push({date:new Date().toISOString(),score,total:qs.length}); localStorage.quizHist=JSON.stringify(hist); alert(`Puntaje ${score}/${qs.length}`);}
function tutor(){return `<section class="card"><h1>Tutor de IA para Programación Lineal</h1><div class="alert danger">No sustituye la verificación del profesor. No comparta datos sensibles. Modo integrable requiere backend seguro.</div><label>Pregunta<input id="chatIn" placeholder="¿Cómo formulo restricciones de capacidad?"></label><button class="btn" onclick="demoChat()">Enviar en modo demo</button><div id="chatOut" class="card" aria-live="polite"></div><h2>Modo integrable</h2><p>Use el backend Node/Express incluido en /backend y configure la clave en variables de entorno. Nunca coloque llaves en este frontend.</p></section>`}
window.demoChat=function(){let txt=$('#chatIn').value.toLowerCase(); let ans=txt.includes('dual')?'El dual interpreta recursos y precios sombra; verifique signos según max/min.':'Empiece definiendo variables de decisión, función objetivo, restricciones y no negatividad. Luego revise unidades y sentido de desigualdad.'; $('#chatOut').innerHTML+=`<p><b>Estudiante:</b> ${txt}</p><p><b>Tutor demo:</b> ${ans}</p>`}
function glossary(){return `<section class="card"><h1>Glosario y hoja de fórmulas imprimible</h1>${tbl({'D':'Demanda anual','K':'Costo de ordenar/setup','h':'Costo de mantener por unidad-año','Q':'Cantidad de pedido/lote','λ':'Tasa de llegadas','μ':'Tasa de servicio','ρ':'Utilización','L, Lq':'Clientes esperados en sistema y cola','W, Wq':'Tiempo esperado en sistema y cola'},'Símbolos principales')}<button class="btn" onclick="print()">Imprimir / guardar PDF</button></section>`}
function route(){side();let h=location.hash||'#/inicio';let parts=h.split('/'); let html=h.includes('ejercicios')?exercises():h.includes('quices')?quizzes():h.includes('tutor')?tutor():h.includes('glosario')?glossary():parts[1]==='modulo'?modulePage(parts[2]):home(); $('#main').innerHTML=html; if($('#invChart')) drawInventory(); if($('#qOut')) calcQueue(); mj();}
addEventListener('hashchange',route); addEventListener('DOMContentLoaded',()=>{$('#search').addEventListener('input',side);route();});
