const D=window.IO_DATA; const $=s=>document.querySelector(s); const fmt=n=>Number.isFinite(Number(n))?Number(n).toFixed(3):'N/D';
function mj(){ if(window.MathJax?.typesetPromise) MathJax.typesetPromise(); }
function side(){ const q=($('#search')?.value||'').toLowerCase(); $('#sideList').innerHTML='<h3>Inventarios</h3>'+D.modules.filter(m=>m.kind==='inventory'&&JSON.stringify(m).toLowerCase().includes(q)).map(m=>`<a class="module-link" href="#/modulo/${m.slug}">${m.title}</a>`).join('')+'<h3>Colas</h3>'+D.modules.filter(m=>m.kind==='queue'&&JSON.stringify(m).toLowerCase().includes(q)).map(m=>`<a class="module-link" href="#/modulo/${m.slug}">${m.title}</a>`).join('');}
function tbl(obj,cap='Datos del caso'){return `<table><caption>${cap}</caption><thead><tr><th>Parámetro</th><th>Valor</th></tr></thead><tbody>${Object.entries(obj).map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</tbody></table>`}
function progress(){let done=JSON.parse(localStorage.ioDone||'[]').length; return `<div class="card"><b>Progreso:</b> ${done}/${D.modules.length} módulos marcados.<div class="progress" aria-label="Progreso"><span style="width:${100*done/D.modules.length}%"></span></div></div>`}

function renderTheory(m){
 const t=m.theory||{};
 if(!t.overview) return '';
 const vars=(t.variables||[]).map(v=>`<tr><td>${v.s}</td><td>${v.d}</td></tr>`).join('');
 const block=(title,items)=>items?.length?`<section class="theory-block"><h3>${title}</h3>${items.map(x=>`<p>${x}</p>`).join('')}</section>`:'';
 const list=(title,items)=>items?.length?`<section class="theory-block"><h3>${title}</h3><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul></section>`:'';
 return `<section class="card theory"><h2>Marco teórico ampliado del modelo</h2>
 ${block('Descripción detallada',t.overview)}
 ${list('Supuestos del modelo',t.assumptions)}
 ${vars?`<section class="theory-block"><h3>Variables y parámetros</h3><table><caption>Notación principal del modelo</caption><thead><tr><th>Símbolo</th><th>Interpretación operacional</th></tr></thead><tbody>${vars}</tbody></table></section>`:''}
 ${list('Problemas de aplicación típicos',t.applications)}
 <div class="grid two">${list('Ventajas',t.advantages)}${list('Desventajas y limitaciones',t.limitations)}</div>
 ${list('Chequeos de validación antes de aplicar',t.validation)}
 <details><summary>Lecturas recomendadas y base académica</summary><p>Anderson, Sweeney, Williams, Camm & Martin, <em>An Introduction to Management Science</em>, capítulos de inventarios y waiting lines; Winston, <em>Operations Research</em>; Hillier & Lieberman, <em>Introduction to Operations Research</em>. Cuando el sitio usa datos no verificables, se etiquetan como simulados.</p></details>
 </section>`;
}
function home(){return `<section class="card"><h1>Ecosistema web de Investigación de Operaciones</h1><p>Aprendizaje riguroso de inventarios y teoría de colas con MathJax, gráficos Chart.js, ejercicios, quices y tutor demo.</p><div class="alert">Las tablas de práctica usan datos simulados cuando no se declara una fuente verificable.</div></section>${progress()}<section class="grid">${D.modules.map(m=>`<article class="card"><h2>${m.title}</h2><p>${m.area}</p><a class="btn" href="#/modulo/${m.slug}">Abrir módulo</a></article>`).join('')}</section>`}
function modulePage(slug){const m=D.modules.find(x=>x.slug===slug); if(!m)return home(); let html=`<article class="card"><p class="muted">Inicio › ${m.area} › ${m.title}</p><h1>${m.title}</h1><p><b>Modelo y supuestos.</b> Este módulo define variables, función objetivo/métricas, condiciones de aplicación y limitaciones. Fórmula guía: $$${m.formula}$$</p><div class="alert"><b>Lecturas recomendadas:</b> Anderson, Sweeney, Williams, Camm & Martin, capítulo de inventarios/colas; Winston, Operations Research; Hillier & Lieberman, Introduction to Operations Research.</div><button class="btn" onclick="markDone('${m.slug}')">Marcar módulo como completado</button></article>`;
 html+=renderTheory(m);
 if(m.kind==='inventory') html+=inventoryLab(m); else html+=queueLab(m);
 html+=`<section class="card"><h2>10 ejemplos resueltos</h2>${m.examples.map(ex=>`<article class="example"><h3>${ex.title}</h3><p>${ex.statement}</p><p class="muted">Fuente: ${ex.source}</p>${tbl(ex.data)}<ol>${ex.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p><b>Interpretación:</b> ${ex.managerial}</p><details><summary>Errores comunes</summary><ul>${ex.errors.map(e=>`<li>${e}</li>`).join('')}</ul></details></article>`).join('')}</section><section class="card"><h2>Mini-resumen</h2><ul>${m.summary.map(x=>`<li>${x}</li>`).join('')}</ul></section>`; return html;}
function inventoryLab(m){return `<section class="card lab" data-slug="${m.slug}" data-kind="inventory"><h2>Laboratorio interactivo de inventario — ${m.title}</h2><p>Use este laboratorio para observar cómo cambian la política recomendada y las curvas de costo cuando se modifican los parámetros. Los gráficos se actualizan automáticamente y también funcionan sin conexión mediante un trazado básico en canvas si Chart.js no está disponible.</p><div class="controls"><label>D demanda anual<input id="Dval" type="number" min="1" value="2400"></label><label>K costo ordenar/setup<input id="Kval" type="number" min="0.01" value="80"></label><label>h costo mantener<input id="hval" type="number" min="0.01" value="4"></label>${inventoryExtraControls(m.slug)}<button class="btn" id="invBtn" type="button">Actualizar gráficos</button></div><p id="invOut" class="alert" aria-live="polite"></p><div class="grid two"><figure><canvas id="invChart" height="260" aria-label="Inventario contra tiempo" role="img"></canvas><figcaption id="invInterpret" class="lab-help"></figcaption></figure><figure><canvas id="costChart" height="260" aria-label="Costo total contra cantidad" role="img"></canvas><figcaption id="costInterpret" class="lab-help"></figcaption></figure></div><details open><summary>Cómo interpretar este laboratorio</summary><div id="labTheory" class="lab-help"></div></details></section>`}
function inventoryExtraControls(slug){
 if(slug==='agotados-eoq') return `<label>b costo faltante<input id="bval" type="number" min="0.01" value="12"></label>`;
 if(slug==='epq') return `<label>P producción anual<input id="Pval" type="number" min="1" value="9000"></label>`;
 if(slug==='incertidumbre-eoq') return `<label>σ demanda durante LT<input id="sigval" type="number" min="0" value="60"></label><label>z nivel servicio<input id="zval" type="number" step="0.01" value="1.65"></label>`;
 if(slug==='newsvendor') return `<label>Cu subinventario<input id="cuval" type="number" min="0.01" value="15"></label><label>Co sobreinventario<input id="coval" type="number" min="0.01" value="5"></label>`;
 if(slug==='descuentos-eoq') return `<label>c costo unitario<input id="cval" type="number" min="0.01" value="20"></label><label>descuento %<input id="discval" type="number" min="0" max="80" value="8"></label>`;
 return '';
}
function queueLab(m){return `<section class="card lab" data-slug="${m.slug}" data-kind="queue"><h2>Laboratorio interactivo de colas — ${m.title}</h2><p>Ingrese tasas compatibles en clientes por hora. El laboratorio valida estabilidad, calcula métricas principales y grafica el efecto de la carga sobre tiempos y congestión.</p><div class="controls"><label>λ llegadas/h<input id="lam" type="number" min="0.01" value="5" step=".1"></label><label>μ servicio/h por servidor<input id="mu" type="number" min="0.01" value="8" step=".1"></label><label>Servidores s<input id="serv" type="number" min="1" value="${m.slug==='mm1'||m.slug==='mg1'||m.slug==='mm1gdc'?1:2}"></label>${queueExtraControls(m.slug)}<button class="btn" id="qBtn" type="button">Calcular</button></div><p id="qOut" class="alert" aria-live="polite"></p><div class="grid two"><figure><canvas id="queueMetricChart" height="260" aria-label="Métricas de cola" role="img"></canvas><figcaption id="queueMetricInterpret" class="lab-help"></figcaption></figure><figure><canvas id="queueSensitivityChart" height="260" aria-label="Sensibilidad de espera a lambda" role="img"></canvas><figcaption id="queueSensitivityInterpret" class="lab-help"></figcaption></figure></div><details open><summary>Cómo interpretar este laboratorio</summary><div id="qLabTheory" class="lab-help"></div></details></section>`}
function queueExtraControls(slug){
 if(slug==='mg1'||slug==='mgs'||slug==='mgsgds') return `<label>CV servicio<input id="cvval" type="number" min="0" step="0.1" value="1.2"></label>`;
 if(slug==='mm1gdc'||slug==='mgsgds') return `<label>Capacidad c/K<input id="capval" type="number" min="1" value="10"></label>`;
 if(slug==='mmr-gdkk') return `<label>K máquinas<input id="Kpop" type="number" min="1" value="8"></label><label>α fallas/máquina-h<input id="alphaval" type="number" min="0.001" step="0.01" value="0.2"></label>`;
 return '';
}
let charts=[]; function clearCharts(){charts.forEach(c=>{try{c.destroy()}catch(e){}}); charts=[]}
function hasChart(){return typeof window.Chart==='function'}
function simpleLineCanvas(canvas, series, labels, yLabel){
 const ctx=canvas?.getContext?.('2d'); if(!ctx) return; const w=canvas.width=canvas.clientWidth||520, h=canvas.height=260; ctx.clearRect(0,0,w,h); ctx.font='12px Arial'; ctx.strokeRect(42,15,w-55,h-55); const all=series.flatMap(s=>s.data).filter(Number.isFinite); const max=Math.max(...all,1), min=Math.min(...all,0); series.forEach((s,idx)=>{ctx.beginPath(); s.data.forEach((v,i)=>{const x=42+(w-60)*(i/(s.data.length-1||1)); const y=15+(h-55)*(1-(v-min)/(max-min||1)); i?ctx.lineTo(x,y):ctx.moveTo(x,y);}); ctx.stroke(); ctx.fillText(s.label,55,28+idx*14);}); ctx.fillText(labels?.[0]||'',42,h-22); ctx.fillText(labels?.[labels.length-1]||'',w-95,h-22); ctx.fillText(yLabel||'',8,15); }
function renderChart(canvas, config, fallbackSeries, fallbackLabels, yLabel){
 if(hasChart()){charts.push(new Chart(canvas, config));} else {simpleLineCanvas(canvas, fallbackSeries, fallbackLabels, yLabel);}
}
function posValue(id, name){ const v=+($('#'+id)?.value); if(!Number.isFinite(v)||v<=0) throw new Error(`${name} debe ser positivo.`); return v; }
function currentInventoryResult(slug,Dv,K,h){
 let q=Math.sqrt(2*Dv*K/h), note='EOQ clásico: se balancean costo de ordenar y costo de mantener.';
 let maxInv=q, cycle=q/Dv*365, extra={};
 if(slug==='agotados-eoq'){const b=posValue('bval','b'); q=Math.sqrt((2*Dv*K/h)*((h+b)/b)); const S=(h/(h+b))*q; maxInv=q-S; extra.S=S; note='EOQ con faltantes planeados: parte del ciclo permite backorders; el inventario máximo es menor que Q porque una fracción del lote cubre pedidos pendientes.';}
 if(slug==='epq'){const P=posValue('Pval','P'); if(P<=Dv) throw new Error('En EPQ, P debe ser mayor que D para que el inventario pueda acumularse.'); q=Math.sqrt((2*Dv*K)/(h*(1-Dv/P))); maxInv=q*(1-Dv/P); extra.P=P; note='EPQ: el reabastecimiento ocurre gradualmente; por eso el inventario máximo es Q(1-D/P), no Q.';}
 if(slug==='incertidumbre-eoq'){const sig=+($('#sigval')?.value||0), z=+($('#zval')?.value||0); extra.ss=z*sig; extra.rop=(Dv/365)*7+extra.ss; note='EOQ bajo incertidumbre: Q controla frecuencia de pedido y el punto de reorden incorpora stock de seguridad para proteger el lead time.';}
 if(slug==='newsvendor'){const cu=posValue('cuval','Cu'), co=posValue('coval','Co'); extra.crit=cu/(cu+co); q=Dv/365*(1+extra.crit); maxInv=q; cycle=1; note='Newsvendor: la decisión es de un solo periodo; la razón crítica indica el percentil de demanda que conviene cubrir.';}
 return {q,maxInv,cycle,note,extra};
}
window.drawInventory=function(slug=(document.querySelector('.lab')?.dataset.slug||'eoq-basico')){clearCharts();try{let Dv=posValue('Dval','D'),K=posValue('Kval','K'),h=posValue('hval','h'); let r=currentInventoryResult(slug,Dv,K,h); let q=r.q; let ctot=Dv/q*K+q/2*h; let extraText=''; if(r.extra.S) extraText+=` Faltante máximo planeado S=${fmt(r.extra.S)}.`; if(r.extra.ss!==undefined) extraText+=` Stock de seguridad=${fmt(r.extra.ss)}; ROP aproximado=${fmt(r.extra.rop)} unidades.`; if(r.extra.crit) extraText+=` Razón crítica=${fmt(r.extra.crit)}.`; $('#invOut').innerHTML=`Resultado: $$Q^*=${fmt(q)}\text{ unidades},\quad CT=${fmt(ctot)}\text{ por año}.$$ ${extraText}`; let t=[0,.25,.5,.75,1].map(x=>x*r.cycle); let inv=[r.maxInv,.75*r.maxInv,.5*r.maxInv,.25*r.maxInv,0]; if(slug==='epq'){inv=[0,.75*r.maxInv,r.maxInv,.5*r.maxInv,0];}
 const invCfg={type:'line',data:{labels:t.map(x=>fmt(x)),datasets:[{label:'Inventario disponible (unidades)',data:inv,tension:.2}]},options:{responsive:true,plugins:{legend:{display:true},title:{display:true,text:'Evolución del inventario en un ciclo'}},scales:{x:{title:{display:true,text:'Tiempo (días)'}},y:{title:{display:true,text:'Unidades'}}}}};
 renderChart($('#invChart'),invCfg,[{label:'Inventario disponible',data:inv}],t.map(x=>fmt(x)),'Unidades');
 let qs=Array.from({length:50},(_,i)=>Math.max(1,q*.25+i*q*.04)); let total=qs.map(x=>Dv/x*K+x/2*h), ord=qs.map(x=>Dv/x*K), hold=qs.map(x=>x/2*h);
 if(slug==='descuentos-eoq'){const c=posValue('cval','c'),disc=Math.max(0,+($('#discval')?.value||0))/100; total=qs.map(x=>Dv/x*K+x/2*h+Dv*c*(x>=q?1-disc:1));}
 const costCfg={type:'line',data:{labels:qs.map(x=>fmt(x)),datasets:[{label:'Costo total ($/año)',data:total,tension:.2},{label:'Costo de ordenar',data:ord,tension:.2},{label:'Costo de mantener',data:hold,tension:.2}]},options:{responsive:true,plugins:{legend:{display:true},title:{display:true,text:'Curvas de costo relevantes'}},scales:{x:{title:{display:true,text:'Cantidad Q (unidades)'}},y:{title:{display:true,text:'Costo anual ($/año)'}}}}};
 renderChart($('#costChart'),costCfg,[{label:'Costo total',data:total},{label:'Ordenar',data:ord},{label:'Mantener',data:hold}],qs.map(x=>fmt(x)),'$/año');
 $('#invInterpret').innerHTML=`<b>Interpretación del gráfico de inventario:</b> la línea muestra el patrón de consumo/reposición del modelo ${slug}. Cuando la pendiente baja, la demanda consume unidades; cuando sube o reinicia el ciclo, ocurre el pedido o la producción. El valor máximo observado representa el inventario expuesto a costo de mantenimiento. ${r.note}`;
 $('#costInterpret').innerHTML=`<b>Interpretación del gráfico de costos:</b> el mínimo de la curva de costo total identifica la zona económicamente atractiva. A la izquierda del mínimo se hacen demasiados pedidos y domina el costo de ordenar; a la derecha se compra o produce demasiado y domina el costo de mantener. Si la curva es plana cerca del mínimo, pequeños redondeos de Q tienen bajo impacto.`;
 $('#labTheory').innerHTML=inventoryLabExplanation(slug);
 mj(); }catch(e){$('#invOut').textContent='Error: '+e.message;}}
function inventoryLabExplanation(slug){const map={
 'eoq-basico':'En EOQ básico, el punto óptimo aparece cuando el ahorro por reducir pedidos se compensa con el mayor inventario promedio. Úselo cuando la demanda sea relativamente estable y no existan descuentos ni faltantes permitidos.',
 'sensibilidad-eoq':'En sensibilidad EOQ, observe que la curva de costo total suele ser poco empinada alrededor de Q*. Esto explica por qué la política puede tolerar redondeos o empaques mínimos sin gran pérdida económica.',
 'descuentos-eoq':'En descuentos por cantidad, la curva puede presentar saltos o cambios de nivel por reducción del costo unitario. No basta con calcular EOQ: se deben comparar tramos factibles y costo total con compra.',
 'agotados-eoq':'En EOQ con faltantes planeados, el gráfico debe leerse distinguiendo inventario positivo y demanda pendiente. Mayor costo de faltante reduce la zona de backorders y acerca el modelo al EOQ sin faltantes.',
 'epq':'En EPQ, el inventario crece durante la producción porque la tasa P supera a D; después decrece cuando termina el lote. Si P se aproxima a D, el sistema pierde capacidad de acumular inventario.',
 'incertidumbre-eoq':'En EOQ probabilístico, Q no elimina el riesgo. El punto de reorden y el stock de seguridad son los elementos que protegen contra variabilidad de demanda y lead time.',
 'newsvendor':'En Newsvendor, la lectura cambia de ciclo repetitivo a decisión de un periodo. La razón crítica muestra cuánto riesgo de sobrante se acepta para evitar faltantes.'}; return `<p>${map[slug]||map['eoq-basico']}</p><p><b>Chequeo:</b> mantenga unidades consistentes: D en unidades/año, K en $/pedido y h en $/unidad-año. Si cambia la unidad de tiempo, cambie todas las tasas.</p>`;}
function factorial(n){let r=1; for(let i=2;i<=n;i++) r*=i; return r;}
function mmcMetrics(l,mu,s){const a=l/mu, rho=l/(s*mu); if(rho>=1) return {rho,stable:false}; let sum=0; for(let n=0;n<s;n++) sum+=Math.pow(a,n)/factorial(n); const last=Math.pow(a,s)/(factorial(s)*(1-rho)); const P0=1/(sum+last); const Lq=P0*Math.pow(a,s)*rho/(factorial(s)*Math.pow(1-rho,2)); const Wq=Lq/l, W=Wq+1/mu, L=l*W; return {rho,P0,Lq,Wq,W,L,stable:true};}
function finiteMM1(l,mu,K){let r=l/mu, P0=(Math.abs(r-1)<1e-9)?1/(K+1):(1-r)/(1-Math.pow(r,K+1)); let probs=Array.from({length:K+1},(_,n)=>P0*Math.pow(r,n)); let PK=probs[K], le=l*(1-PK); let L=probs.reduce((a,p,n)=>a+n*p,0); let W=L/le, Lq=Math.max(0,L-(1-P0)); let Wq=Lq/le; return {rho:r,P0,Lq,Wq,W,L,PK,lambdaEff:le,stable:true};}
function machineRepair(K,alpha,mu,s){let weights=[]; for(let n=0;n<=K;n++){let w=1; for(let i=0;i<n;i++) w*=((K-i)*alpha)/(Math.min(i+1,s)*mu); weights.push(w);} let total=weights.reduce((a,b)=>a+b,0); let probs=weights.map(w=>w/total); let L=probs.reduce((a,p,n)=>a+n*p,0); let busy=probs.reduce((a,p,n)=>a+Math.min(n,s)*p,0); let throughput=busy*mu; let W=L/throughput; let Lq=probs.reduce((a,p,n)=>a+Math.max(0,n-s)*p,0); return {rho:busy/s,P0:probs[0],Lq,Wq:Lq/throughput,W,L,stable:true,lambdaEff:throughput};}
function queueCompute(slug,l,mu,s){
 if(slug==='mmr-gdkk'){const K=posValue('Kpop','K'), alpha=posValue('alphaval','α'); return machineRepair(Math.round(K),alpha,mu,s);}
 if(slug==='mm1gdc'||slug==='mgsgds'){const cap=Math.round(posValue('capval','capacidad')); return finiteMM1(l,mu,cap);}
 let met=mmcMetrics(l,mu,s); if(!met.stable) return met;
 if(slug==='mg1'||slug==='mgs'||slug==='mgsgds'){const cv=Math.max(0,+($('#cvval')?.value||1)); const adj=(1+cv*cv)/2; met.Lq*=adj; met.Wq=met.Lq/l; met.W=met.Wq+1/mu; met.L=l*met.W; met.cv=cv;}
 return met;
}
window.calcQueue=function(slug=(document.querySelector('.lab')?.dataset.slug||'mm1')){clearCharts();try{let l=posValue('lam','λ'),mu=posValue('mu','μ'),s=Math.max(1,Math.round(posValue('serv','s'))); if((slug==='mm1'||slug==='mg1'||slug==='mm1gdc')&&s!==1){s=1; $('#serv').value=1;} let met=queueCompute(slug,l,mu,s); if(!met.stable){$('#qOut').innerHTML=`ρ=${fmt(met.rho)}. Sistema inestable para cola infinita: se requiere $\lambda < s\mu$.`; mj(); return;} $('#qOut').innerHTML=`Resultados: $$\rho=${fmt(met.rho)},\quad P_0=${fmt(met.P0)},\quad L_q=${fmt(met.Lq)},\quad W_q=${fmt(met.Wq)}h,\quad W=${fmt(met.W)}h,\quad L=${fmt(met.L)}.$$ ${met.PK!==undefined?`Probabilidad de bloqueo/capacidad llena: ${fmt(met.PK)}. `:''}${met.lambdaEff?`Tasa efectiva: ${fmt(met.lambdaEff)} clientes/h.`:''}`;
 const labels=['ρ','Lq','L','Wq h','W h']; const vals=[met.rho,met.Lq,met.L,met.Wq,met.W];
 const metricCfg={type:'bar',data:{labels,datasets:[{label:'Métricas calculadas',data:vals}]},options:{responsive:true,plugins:{legend:{display:true},title:{display:true,text:'Resumen operativo del sistema'}},scales:{y:{title:{display:true,text:'Valor de la métrica'}}}}};
 renderChart($('#queueMetricChart'),metricCfg,[{label:'Métricas',data:vals}],labels,'Valor');
 let xs=Array.from({length:25},(_,i)=>Math.max(.01,l*.2+i*(Math.max(l*1.6,.1))/24)); let waits=xs.map(x=>{let z=queueCompute(slug,x,mu,s); return z.stable?z.Wq:null}); let waitsFinite=waits.map(v=>Number.isFinite(v)?v:NaN).filter(Number.isFinite);
 const sensCfg={type:'line',data:{labels:xs.map(x=>fmt(x)),datasets:[{label:'Wq esperado (horas)',data:waits,borderWidth:2,tension:.2}]},options:{responsive:true,plugins:{legend:{display:true},title:{display:true,text:'Sensibilidad del tiempo de espera ante λ'}},scales:{x:{title:{display:true,text:'λ llegadas por hora'}},y:{title:{display:true,text:'Wq (horas)'}}}}};
 renderChart($('#queueSensitivityChart'),sensCfg,[{label:'Wq esperado',data:waitsFinite}],xs.map(x=>fmt(x)),'Horas');
 $('#queueMetricInterpret').innerHTML=`<b>Interpretación del gráfico de métricas:</b> compare utilización, longitud esperada y tiempos. Una ρ cercana a 1 significa alta ocupación, pero también congestión. L y Lq están en clientes; W y Wq están en horas. En decisiones gerenciales, Wq suele ser la métrica clave de experiencia del usuario.`;
 $('#queueSensitivityInterpret').innerHTML=`<b>Interpretación del gráfico de sensibilidad:</b> al aumentar λ, la espera crece de forma no lineal. En colas infinitas, cuando λ se acerca a sμ, el tiempo de espera tiende a dispararse; por eso operar con utilización muy alta puede deteriorar el servicio aunque parezca eficiente.`;
 $('#qLabTheory').innerHTML=queueLabExplanation(slug);
 mj(); }catch(e){$('#qOut').textContent='Error: '+e.message;}}
function queueLabExplanation(slug){const map={
 'mm1':'M/M/1 supone llegadas Poisson, servicio exponencial y un servidor. Es útil para ventanillas simples, cajeros únicos o estaciones individuales donde se busca entender la relación entre utilización y espera.',
 'mms':'M/M/s generaliza a varios servidores paralelos. La curva de sensibilidad ayuda a decidir si agregar un servidor reduce Wq de forma suficiente frente al costo adicional.',
 'mg1':'M/G/1 conserva llegadas Poisson pero permite servicio general. El coeficiente de variación del servicio incrementa o reduce la espera: mayor variabilidad genera colas más largas.',
 'mgs':'M/G/s combina varios servidores con servicio no necesariamente exponencial. El laboratorio usa una aproximación didáctica para mostrar el efecto de variabilidad; para decisiones críticas conviene simular o aplicar fórmulas especializadas.',
 'mm1gdc':'M/M/1/GD/c/∞ representa una cola con capacidad finita. Interprete la probabilidad de bloqueo como demanda que no logra entrar al sistema cuando está lleno.',
 'mgsgds':'M/G/s/GD/s/∞ representa servicio general y capacidad limitada. La disciplina GD afecta el orden de atención; las métricas promedio no siempre capturan equidad o prioridad.',
 'mmr-gdkk':'El modelo de reparación de máquinas tiene población finita: la tasa de llegadas depende de cuántas máquinas siguen operando. No use λ externa fija; la tasa efectiva surge del número de máquinas activas.'}; return `<p>${map[slug]||map.mm1}</p><p><b>Chequeo:</b> para colas de población infinita valide siempre $\rho=\lambda/(s\mu)<1$. Para capacidad finita, revise además probabilidad de bloqueo y tasa efectiva.</p>`;}
window.markDone=function(slug){let a=JSON.parse(localStorage.ioDone||'[]'); if(!a.includes(slug))a.push(slug); localStorage.ioDone=JSON.stringify(a); location.reload();}
function exercises(){return `<section class="card"><h1>Banco de ejercicios y casos</h1><p>Incluye ${D.exercises.length} problemas. Las soluciones están únicamente en Sitio B.</p></section>`+D.exercises.map(e=>`<article class="card"><h2>${e.id} · ${e.title}</h2><span class="pill">${e.difficulty}</span><span class="pill">${e.topic}</span><span class="pill">${e.time}</span><p>${e.context}</p><p class="muted">Fuente: ${e.source}</p>${tbl(e.data)}<ol>${e.questions.map(q=>`<li>${q}</li>`).join('')}</ol><label>Entrega del estudiante<textarea aria-label="Respuesta ${e.id}" data-answer="${e.id}" placeholder="Escriba aquí su solución..."></textarea></label></article>`).join('')}
function quizzes(){return `<section class="card"><h1>Quices interactivos</h1><button class="btn" onclick="randomQuiz()">Generar quiz aleatorio</button><div id="quizArea"></div></section>`+D.quizzes.map(q=>`<article class="card"><h2>${q.title}</h2><p>${q.questions.length} preguntas.</p><button class="btn" onclick="startQuiz('${q.id}')">Iniciar</button></article>`).join('')}
window.startQuiz=function(id){const qz=D.quizzes.find(q=>q.id===id); renderQuiz(qz.questions,qz.title)}; window.randomQuiz=function(){let pool=D.quizzes.flatMap(q=>q.questions); renderQuiz(pool.sort(()=>Math.random()-.5).slice(0,15),'Quiz aleatorio')}
function renderQuiz(qs,title){$('#quizArea').innerHTML=`<h2>${title}</h2>`+qs.map((q,i)=>`<div class="card"><b>${i+1}. ${q.prompt}</b>${q.type==='mc'?q.options.map((o,j)=>`<label class="quiz-option"><input name="q${i}" type="radio" value="${j}"> ${o}</label>`).join(''):q.type==='tf'?`<label><select id="ans${i}"><option value="true">Verdadero</option><option value="false">Falso</option></select></label>`:q.type==='num'?`<input id="ans${i}" type="number" step=".01">`:`<p>${Object.keys(q.pairs).join(', ')} ↔ ${Object.values(q.pairs).join(', ')}</p><input id="ans${i}" placeholder="D=demanda;K=costo...">`}<p id="fb${i}" class="muted"></p></div>`).join('')+`<button class="btn" onclick='gradeQuiz(${JSON.stringify(qs).replace(/'/g,"&#39;")})'>Calificar</button>`; mj()}
window.gradeQuiz=function(qs){let score=0; qs.forEach((q,i)=>{let ok=false;if(q.type==='mc'){let v=document.querySelector(`input[name=q${i}]:checked`); ok=v&&+v.value===q.answer}else if(q.type==='tf'){ok=($('#ans'+i).value==='true')===q.answer}else if(q.type==='num'){ok=Math.abs(+$('#ans'+i).value-q.answer)<=q.tol}else ok=($('#ans'+i).value||'').toLowerCase().includes('demanda'); if(ok)score++; $('#fb'+i).innerHTML=(ok?'Correcto. ':'Revisar. ')+q.feedback}); let hist=JSON.parse(localStorage.quizHist||'[]'); hist.push({date:new Date().toISOString(),score,total:qs.length}); localStorage.quizHist=JSON.stringify(hist); alert(`Puntaje ${score}/${qs.length}`);}
function tutor(){return `<section class="card"><h1>Tutor de IA para Programación Lineal</h1><div class="alert danger">No sustituye la verificación del profesor. No comparta datos sensibles. Modo integrable requiere backend seguro.</div><label>Pregunta<input id="chatIn" placeholder="¿Cómo formulo restricciones de capacidad?"></label><button class="btn" onclick="demoChat()">Enviar en modo demo</button><div id="chatOut" class="card" aria-live="polite"></div><h2>Modo integrable</h2><p>Use el backend Node/Express incluido en /backend y configure la clave en variables de entorno. Nunca coloque llaves en este frontend.</p></section>`}
window.demoChat=function(){let txt=$('#chatIn').value.toLowerCase(); let ans=txt.includes('dual')?'El dual interpreta recursos y precios sombra; verifique signos según max/min.':'Empiece definiendo variables de decisión, función objetivo, restricciones y no negatividad. Luego revise unidades y sentido de desigualdad.'; $('#chatOut').innerHTML+=`<p><b>Estudiante:</b> ${txt}</p><p><b>Tutor demo:</b> ${ans}</p>`}
function glossary(){return `<section class="card"><h1>Glosario y hoja de fórmulas imprimible</h1>${tbl({'D':'Demanda anual','K':'Costo de ordenar/setup','h':'Costo de mantener por unidad-año','Q':'Cantidad de pedido/lote','λ':'Tasa de llegadas','μ':'Tasa de servicio','ρ':'Utilización','L, Lq':'Clientes esperados en sistema y cola','W, Wq':'Tiempo esperado en sistema y cola'},'Símbolos principales')}<button class="btn" onclick="print()">Imprimir / guardar PDF</button></section>`}
function initLabs(){const lab=document.querySelector('.lab'); if(!lab) return; const slug=lab.dataset.slug; if(lab.dataset.kind==='inventory'){document.querySelectorAll('#Dval,#Kval,#hval,#bval,#Pval,#sigval,#zval,#cuval,#coval,#cval,#discval').forEach(el=>el?.addEventListener('input',()=>drawInventory(slug))); $('#invBtn')?.addEventListener('click',()=>drawInventory(slug)); drawInventory(slug);} else {document.querySelectorAll('#lam,#mu,#serv,#cvval,#capval,#Kpop,#alphaval').forEach(el=>el?.addEventListener('input',()=>calcQueue(slug))); $('#qBtn')?.addEventListener('click',()=>calcQueue(slug)); calcQueue(slug);} }
function route(){side();let h=location.hash||'#/inicio';let parts=h.split('/'); let html=h.includes('ejercicios')?exercises():h.includes('quices')?quizzes():h.includes('tutor')?tutor():h.includes('glosario')?glossary():parts[1]==='modulo'?modulePage(parts[2]):home(); $('#main').innerHTML=html; initLabs(); mj();}
addEventListener('hashchange',route); addEventListener('DOMContentLoaded',()=>{$('#search').addEventListener('input',side);route();});
